# typed: false
# frozen_string_literal: true

# doz-canary — Dozer Sandbox's command-line tool, the canary channel (every build first: canary, beta and stable).
# GENERATED by `make publish` / `make promote` in the dozer-sandbox repository (Scripts/feed.py formulas) —
# never edit it here: the next publish rewrites it. One formula per release channel (doz, doz-beta,
# doz-canary); they install the same `doz` command, so only one can be installed at a time —
# `doz upgrade --channel stable|beta|canary` switches between them (your store and settings stay).
class DozCanary < Formula
  desc "Fast, suspendable Linux sandboxes (micro-VMs) for your Mac"
  homepage "https://github.com/dozer-sandbox/dozer-sandbox"
  url "https://github.com/dozer-sandbox/dozer-sandbox/releases/download/v0.32.0/doz-0.32.0-macos-arm64.tar.gz"
  version "0.32.0"
  sha256 "c8b3c5d27715306d6b097abe7c8b3dcc89e40511a220d6f995da572b7b516ce8"
  license "MIT"

  conflicts_with "doz", because: "it installs the same doz command (another release channel)"
  conflicts_with "doz-beta", because: "it installs the same doz command (another release channel)"

  depends_on arch: :arm64
  depends_on macos: :tahoe

  def install
    # The release's layout: the executable, its VERSION and RELEASE marker and its resource bundles (the guest
    # binaries, the web UI) together in libexec/doz — doz finds them beside itself, through the bin link.
    libexec.install Dir["libexec/*"]
    bin.install_symlink libexec/"doz/doz"
  end

  # A host of the previous build keeps running (it runs its own copy) until `doz host restart`; say so.
  # `doz host upgrade-check` never starts or stops one and always exits 0.
  post_install_steps do
    run "libexec/doz/doz", base: :prefix, args: ["host", "upgrade-check"], must_succeed: false, print_stdout: true
  end

  def caveats
    <<~EOS
      Next: doz onboard   (checks this Mac, your agent's account, and prepares an image)

      To upgrade: doz upgrade -y   (it refreshes this tap first — a bare `brew upgrade doz-canary` can miss a
      release for up to a day; doz also tells you when one is out: the setting updates.mode — notify,
      auto or off; doz upgrade --check looks now)

      Upgrading while a doz host runs is safe: it keeps running the previous build until
      `doz host restart` (sandboxes hibernate, and wake on the new build).
      `doz uninstall` removes the store and settings; `brew uninstall doz-canary` removes doz itself.
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/doz --version").strip
    # doctor reads, never starts a host or a VM: a scratch store and settings, nothing created.
    ENV["DOZ_STORE"] = (testpath/"store").to_s
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    ENV["DOZ_UPDATES"] = "off"
    # (doctor exits 1 when any check fails — a test machine may lack the kernel or an agent's login — so
    # the checks that are doz's own are asserted one by one.)
    checks = JSON.parse(shell_output("#{bin}/doz doctor --json || true"))
    status = checks.to_h { |c| [c["check"], c["status"]] }
    assert_equal "ok", status["entitlement"], "doz must carry com.apple.security.virtualization"
    assert_equal "ok", status["guest tools"], "the guest binaries must be found beside doz, in the keg"
    refute_path_exists testpath/"store/host.lock"
  end
end
